changelog:
  categories:
    - title: ğŸ• Features
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
          - fix
    - title: ğŸ‘’ Dependencies
      labels:
        - dependencies
    - title: ğŸ›  BugFix
      labels:
        - fix

